---
title: "01introducao.Rmd"
---

O Brasil possui uma das legislações ambientais mais completas do mundo (CHIAVARI; LOPES, 2017). A Constituição Federal de 1988 estabeleceu regras de competência comuns e concorrentes em relação ao meio ambiente e entes federativos, em seus artigos 22, 23 e 24 (BRASIL, 1988). Como resultado, estados e municípios podem legislar sobre situações mais pontuais, com a cautela de ser subordinada hierarquicamente aos regramentos concorrentes. A não observação deste cuidado pode tornar a lei ou parte dela, inconstitucional.

Para garantir um bom funcionamento de um regramento este deve ser construído baseado na racionalidade. A racionalidade se materializa no uso de instrumentos mais eficientes que garantam que as metas sejam atingidas. Previsibilidade é uma característica essencial de um bom regramento. A previsibilidade é uma forma de garantir que se as rotinas foram realizadas metodicamente, maior será sua confiabilidade e resultados semelhantes serão obtidos, independente de quem as requer ou implemente. Espera-se ainda que o regramento seja eficiente, visando a redução de erros e de custos, das partes envolvidas (ARAGÃO, 1997). Um regramento racional e previsível torna a tramitação eficiente e eficaz, garantindo rapidez, racionalidade, homogeneidade na interpretação das normas, redução dos atritos ou discriminações e padronização. No entanto, há sempre consequências imprevistas pelo legislador que acabam resultando em ineficiências e imperfeições. Dentre as imperfeições mais comuns, tem-se o apego excessivo aos regulamentos, o excesso de formalismo e de papelório, a resistência a mudanças, a dificuldade no atendimento a clientes e os conflitos com o público (CHIAVENATO 2003). 

Um dos objetivos da competência concorrente é contornar a dificuldade de se criar uma legislação ambiental padronizada e linear, ao nível federal (NEUMANN; LOCH, 2002). É extremamente difícil construir uma legislação que dê tratamento coerente às peculiaridades dos distintos ambientes de um país com grande diversidade de biomas como o Brasil. Desta forma, assume-se que as especificidades regionais serão melhor normatizadas pelos estados e municípios por normas suplementares.

A intervenção ambiental é um termo usado na legislação ambiental e pode ser definido como qualquer intervenção sobre a cobertura vegetal nativa ou sobre área de uso restrito, ainda que não implique em supressão de vegetação (MINAS GERAIS, 2019). De forma geral, o processo para solicitação de intervenção ambiental tem como um dos documentos obrigatórios a apresentação de um Inventário Florestal, na hipótese de supressão de vegetação nativa sob regime jurídico específico, ou em quaisquer vegetações com cobertura superior ou igual a dez hectares. 

O documento deve atender a certos requisitos como: erro de amostragem máximo de 10% da média do volume para uma probabilidade de 90% de confiança e validade de 3 anos (MINAS GERAIS, 2013).Cada estado avançou de forma independente quanto aos procedimentos para fiscalização, conferência e validação destes inventários. O Estado de Minas Gerais definiu com Portaria IEF 172/2007 a obrigatoriedade da conferência dos inventários florestais de processos de supressão de vegetação natural para uso alternativo do solo. Atualmente, o escopo da conferência foi expandido para inventários associados a processos de áreas revestidas com qualquer tipologia vegetal nativa primária ou secundária em estágio médio, ou avançado de regeneração suscetíveis de corte, supressão e exploração. A análise do inventário florestal deve ser precedida de vistoria técnica, durante a qual conferem-se no mínimo 10% das parcelas e no mínimo três parcelas por estrato de amostragem definidos no inventário florestal.

Durante a vistoria técnica, o agente de fiscalização sorteia 10% das parcelas presentes no inventário protocolado (assegurando o de mínimo três parcelas). A vistoria é realizada tendo como acompanhante um representante do empreendimento. Os dados do inventário protocolado são comparados com os valores conferidos em campo, permitindo o cálculo do desvio. Os desvios, seja ao nível de parcela, seja ao nível de árvore, podem ser descritos por uma distribuição contendo média e desvio padrão. O objetivo deste artigo é analisar a sensibilidade de diferentes abordagens estatísticas para analisar o inventário protocolado a partir do percentual vistoriado.