---
title: "04discussao.Rmd"
---

É comum ocorrer  consequências imprevistas pelo legislador que acabam resultando em ineficiências e imperfeições. Dentre as imperfeições mais comuns, tem-se o apego excessivo aos regulamentos, o excesso de formalismo e de papelório, a resistência a mudanças, a dificuldade no atendimento a clientes e os conflitos com o público [@chiavenato2003]. 

Para garantir um bom funcionamento de um regramento legal, estes devem ser baseados em alguns valores. A racionalidade é um valor que se materializa no uso de instrumentos  eficientes que garantam que as metas sejam atingidas. Já a previsibilidade é uma forma de garantir que se as rotinas forem realizadas metodicamente, maior será sua confiabilidade e resultados semelhantes serão obtidos, independente de quem as requer ou implemente. A eficiência por sua vez visa a redução de erros e de custos, das partes envolvidas [@aragao1997]. Um regramento racional e previsível torna a tramitação eficiente e eficaz, garantindo rapidez, homogeneidade na interpretação das normas, redução dos atritos ou discriminações e padronização. 

Um dos objetivos da competência concorrente é contornar a dificuldade de se criar uma legislação ambiental padronizada e linear, ao nível federal [@neumann2002]. É extremamente difícil construir uma legislação que dê tratamento coerente às peculiaridades dos distintos ambientes de um país com grande diversidade de biomas como o Brasil. Desta forma, assume-se que as especificidades regionais serão melhor normatizadas pelos estados e municípios por normas suplementares.

A conferência do inventário florestal foi incluída na rotina de processos autorizativos de áreas de supressão pelo Instituto Estadual de Florestal de Minas Gerais em 2007 [@ief172]. Desde então, o procedimento tem sido mantido nas legislações subsequentes. Na prática, este procedimento gera desentendimentos tanto entre os agentes dos órgãos ambientais, quanto entre órgãos e empreendimentos. Questões que vão desde a escolha da estatística de comparação até qual o intervalo máximo entre a medição do empreendimento e a conferência são constantemente questionadas. 

As parcelas conferidas são escolhidas a partir das parcelas lançadas no inventário protocolado, nem sempre as árvores estão identificadas em campo. A realização de uma comparação ao nível de árvores só é possível se houver a identificação de cada indivíduo. A remedição de uma árvore conhecida é que garante o pareamento das medições do empreendimento e da fiscalização. Identificar em campo as árvores é uma prática comum em inventários contínuos, mas raramente aplicado em inventários para solicitação de Autorização de Intervenção Ambiental (AIA). Reconhecendo que existe um erro não amostral embutido na remedição das parcelas, o entendimento de qual abordagem é a mais adequado para comparar a medição do inventário protocolado e conferido passa a ter grande relevância nesse processo.  

Existem diversas abordagens estatísticas que podem ser aplicadas para análise de dois conjuntos de dados.  As abordagens clássicas envolvem a comparação entre dois conjuntos de dados por testes de média (ex: teste t pareado ou teste t não pareado) e testes de aderência entre distribuições (ex: teste de Kolmogorov-Smirnov). Não se avalia aqui o processo amostral, mas sim o processo de mensuração, com o objetivo de verificar se a diferença observada entre dois conjuntos de dados é significativa, ou fruto apenas de um acaso. Na comparação entre protocolado e conferido, o teste t apontou que a diferença média de 0,1 cm no diâmetro já levaria a resultados significativos, enquanto a mesma comparação utilizando o teste Kolmogorov-Smirnov aponta como significativa diferença média a partir de 0,5 cm. Este é um exemplo de testes com diferentes sensibilidades. Onde um teste muito sensível, como é o caso do teste t [@callegari2009] indica uma pequena diferença média na medição diamétrica como significativo, enquanto o teste de KS admite maiores diferenças para a mesma comparação.   

Uma outra abordagem é avaliar como o erro amostral reflete as diferenças observadas entre a medição do empreendimento e a medição de conferência. Neste caso, o foco deixa de ser na medição, e se volta para avaliar a capacidade do delineamento amostral de capturar a variação da população. Os resultados mostram que os desvios na medição diamétrica podem impactar o erro em inventários de empreendimento linear e em floresta nativa. Contudo, não sendo suficientes para extrapolar o limite do erro amostral aceito pelo órgão ambiental (10%). A comparação de erros amostrais com os não amostrais em florestas equiâneas indicou que os erros amostrais do inventário não são afetados pelos erros não amostrais, porém, os erros no diâmetro têm efeito significativo na estimativa de volume por hectare quando este ocorre em mais de 30% dos DAPs da parcela [@Kohler2017], ou seja, o erro não amostral só irá impactar diretamente o erro amostral quando observado em grande escala. O que justifica a não extrapolação do erro amostral para os três inventários em questão. Visto que, os erros incidiram em apenas 10% dos diâmetros das parcelas conferidas, como proposto pela metodologia. 

Na prática, é observado um conflito entre a significância estatística e a significância biológica. A diferença estatística entre a medição do inventário protocolado e conferido existe e é provada de forma significativa por testes consagrados no meio. Ainda assim, por se tratar de uma diferença irrisória, a mesma passa a ter pouca relevância sobre o erro amostral dos inventários protocolados.

A questão é que erros não amostrais no inventário podem ser cometidos tanto pelo órgão fiscalizador na conferência das parcelas quanto pelo profissional contratado para a realização do inventário protocolado. Para a questão aqui levantada não importa se o desvio foi mal-intencionado ou não. O fato é que erros podem ocorrer nos dois lados do processo, e que a detecção apenas indica que existe uma variação não amostral, que pode ser de diferença de equipamento, diferença de técnica, ou outra razão. O grande objetivo da conferência é a detecção de fraude ou de prejuízo para a sociedade, e não a simples detecção de desvios.

Quando o agente fiscalizador vai a campo para validar o inventário seu principal objetivo deveria ser identificar erros de amostragem, ou a existência de fraude no processo protocolado junto ao órgão. De certa forma, a fiscalização deveria se concentrar muito mais no erro amostral, do que no desvio de medição, uma vez que o objetivo é garantir confiabilidade na estimativa de rendimento volumétrico. Alternativas interessantes seriam que ao invés da conferência de parcelas, o órgão realizasse um inventário paralelo utilizando técnicas de sensoriamento remoto com aeronaves remotamente pilotadas (RPA), ou mesmo métodos mais rápidos como o Bitterlich.  

O uso de uma amostragem de área variável, como por exemplo Bitterlich, pode ser uma possibilidade [@campos2017]. Muitos autores desenvolveram trabalhos que testam a eficiência e precisão deste método de amostragem em florestas nativas e constataram ser este um método eficiente para se mensurar o volume [@cavalcanti2011; @retslaff2014; @teo2014]. Mesmo não sendo muito usual o método de amostragem por Bitterlich tem a vantagem de ser mais simples e de menor custo do que métodos que exigem alocação de parcela fixa, sendo recomendado principalmente quando há a necessidade de um diagnóstico rápido [@farias2002], o que é o caso da conferência realizada pelo analista do órgão fiscalizador.